 <?php
defined('BASEPATH') OR exit('No direct script access allowed');
//
include(dirname(dirname(__FILE__)).'/Tglindo.php');
// require_once(APPPATH.'controllers/Secure_area.php');
class Frmclaporan_optik extends Secure_area {
	public function __construct() {
		parent::__construct();
		$this->load->model('logistik_farmasi/Frmmlaporan_optik','',TRUE);
		$this->load->model('logistik_farmasi/Frmmpemasok', '', TRUE);
		$this->load->helper('pdf_helper');
		$this->load->helper('url');
		//include(site_url('/application/controllers/Tglindo.php'));
		//echo site_url('/application/controllers/Tglindo.php');
	}
	public function index()
	{
		// redirect('logistik_farmasi/Frmclaporan_optik/data_pendapatan_new','refresh');
	}
	
public function data_optik($tampil_per='', $param1=''){
        $data['title'] = 'Laporan Pengadaan Optik';
        $data['select_pemasok'] = $this->Frmmpemasok->cari_pemasok()->result();
        $tgl_indo=new Tglindo();
        $data['date_title']='<b>'.date("d F Y").'</b>';
        $data['tgl']=date("Y-m-d");

        $data['message_nodata']="<div class=\"content-header\">
			<div class=\"alert alert-danger alert-dismissable\">
				<button class=\"close\" aria-hidden=\"true\" data-dismiss=\"alert\" type=\"button\">×</button>				
			<h4><i class=\"icon fa fa-warning\"></i>
				Silahkan Pilih Tanggal dan Download untuk Melihat Laporan Pengadaan Optik.
			</h4>							
			</div>
		</div>";
        /*$data['message_nodata']="<div class=\"content-header\">
			<div class=\"alert alert-danger alert-dismissable\">
				<button class=\"close\" aria-hidden=\"true\" data-dismiss=\"alert\" type=\"button\">×</button>				
			<h4><i class=\"icon fa fa-close\"></i>
				Under Construction!!
			</h4>							
			</div>
		</div>";*/

        $this->load->view('logistik_farmasi/Frmvlaporan_optik',$data);
    }

    public function download_pengadaan($param1='',$param2='', $filter=''){
        ////EXCEL

        $this->load->library('Excel');

        // Create new PHPExcel object
        $objPHPExcel = new PHPExcel();

        // Set document properties
        $objPHPExcel->getProperties()->setCreator("Mata Palembang")
            ->setLastModifiedBy("Mata Palembang")
            ->setTitle("Laporan Pengadaan Optik")
            ->setSubject("Laporan Pengadaan Optik")
            ->setDescription("Laporan Pengadaan Optik, generated by HMIS.")
            ->setKeywords("Mata Palembangk")
            ->setCategory("Laporan Pengadaan Optik");

        $objReader= PHPExcel_IOFactory::createReader('Excel2007');
        $objReader->setReadDataOnly(true);

        $data_pengadaan=$this->Frmmlaporan_optik->get_data_pengadaan($param1, $param2, $filter)->result();

        $objPHPExcel=$objReader->load(APPPATH.'third_party/lap_pengadaan_optik.xlsx');
        // Set active sheet index to the first sheet, so Excel opens this as the first sheet
        $objPHPExcel->setActiveSheetIndex(0);
        // Add some data
        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('A3')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('A3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('B3')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('B3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('C3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('D3')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('D3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('E3')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('E3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('F3')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('F3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('G')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('G3')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('G3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('H3')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('H3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('I3')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('I3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('J')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('J3')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('J3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->setAutoFilter('A3:O3');

        $objPHPExcel->getActiveSheet()->SetCellValue('A1', "Laporan Pengadaan Optik Per Faktur Periode ".date('d F Y', strtotime($param1))." - ".date('d F Y', strtotime($param2)));
        $objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(18);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:O1');
        $objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);

        $objPHPExcel->getActiveSheet()->SetCellValue('A2', "Filter Berdasarkan: ".$filter);
        $objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setSize(12);
        $objPHPExcel->getActiveSheet()->mergeCells('A2:O2');
        $objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $rowCount = 4;
        $temp = "";
        $i=1;
        $subtotal = 0; $ttot = 0;
        foreach($data_pengadaan as $row){
       		$dis=$row->discount_percent/100;
       		$subtotal=$row->harga*$row->quantity_purchased;
       		$distot=$subtotal*$dis;
       		$vtot=$subtotal-$distot;
       		$ttot+=$vtot;

            if($temp == $row->no_faktur){
                $objPHPExcel->getActiveSheet()->SetCellValue('E'.$rowCount, $row->description);
                $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowCount, $row->quantity_purchased);
                $objPHPExcel->getActiveSheet()->SetCellValue('G'.$rowCount, $row->harga);
                $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowCount, $row->discount_percent);
                $objPHPExcel->getActiveSheet()->SetCellValue('I'.$rowCount, $subtotal);
                $objPHPExcel->getActiveSheet()->SetCellValue('J'.$rowCount, $vtot);
            }else {
                $temp = $row->no_faktur;
                $objPHPExcel->getActiveSheet()->SetCellValue('A'.$rowCount, $row->no_faktur);
                $objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, $row->tgl_kontra_bon);
                $objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, $row->jatuh_tempo);
                $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowCount, $row->company_name);
                $objPHPExcel->getActiveSheet()->SetCellValue('E'.$rowCount, $row->description);
                $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowCount, $row->quantity_purchased);
                $objPHPExcel->getActiveSheet()->SetCellValue('G'.$rowCount, $row->harga);
                $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowCount, $row->discount_percent);
                $objPHPExcel->getActiveSheet()->SetCellValue('I'.$rowCount, $subtotal);
                $objPHPExcel->getActiveSheet()->SetCellValue('J'.$rowCount, $vtot);
            }
            $i++;
            $rowCount++;
        }
        $filename = "Laporan_Pengadaan_Optik_".date('d F Y', strtotime($param1))."-".date('d F Y', strtotime($param2));
        $objPHPExcel->getActiveSheet()->SetCellValue('I'.$rowCount, "Total : ");
        $objPHPExcel->getActiveSheet()->SetCellValue('J'.$rowCount, $ttot);

        // Rename worksheet (worksheet, not filename)
        $objPHPExcel->getActiveSheet()->setTitle('Mata Palembang');

        // Redirect output to a client’s web browser (Excel2007)
        //clean the output buffer
        ob_end_clean();

        //this is the header given from PHPExcel examples.
        //but the output seems somewhat corrupted in some cases.
        //header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        //so, we use this header instead.
        header('Content-type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename="'.$filename.'.xlsx"');
        header('Cache-Control: max-age=0');

        $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        $objWriter->save('php://output');

        //$this->SaveViaTempFile($objWriter);
    }
}
?>