<?php
defined('BASEPATH') OR exit('No direct script access allowed');
// require_once(APPPATH.'controllers/Secure_area.php');
include('Frmcterbilang.php');
class Frmcstok_optik extends Secure_area
{
  public function __construct(){
    parent::__construct();
    $this->load->model('logistik_farmasi/Frmmtransaksi','',TRUE);
    $this->load->model('logistik_farmasi/Frmmpemasok','',TRUE);
    $this->load->model('logistik_farmasi/Frmmdistribusi','',TRUE);
    $this->load->model('logistik_farmasi/Frmmstok_optik','',TRUE);
    $this->load->model('master/Mmobat','',TRUE);
    $this->load->model('farmasi/Frmmdaftar','',TRUE);
    $this->load->model('logistik_farmasi/Frmmpo','',TRUE);
    $this->load->model('logistik_farmasi/Frmmamprah','',TRUE);
    $this->load->library('session');
    $this->load->helper('pdf_helper');
      // load helper dan library
      $this->load->helper(array('form', 'url'));
      $this->load->library('form_validation');
    }

  function index()
    {
    $data['title'] = 'Stok Optik';
    $data['select_gudang'] = $this->Frmmstok_optik->get_data_gudang()->result();

    $login_data = $this->load->get_var("user_info");
    $data['roleid'] = $this->Frmmstok_optik->get_roleid($login_data->userid)->row()->roleid;

    $id_gudang = $this->Frmmstok_optik->get_gudangid($login_data->userid)->result();
    $i=1;

    foreach ($id_gudang as $row) {
      if($i==1){
        $gd = $this->Frmmstok_optik->getdata_gudang_inventory_by_role($row->id_gudang)->result();
      }else {
        $gd = array_merge($gd, $this->Frmmstok_optik->getdata_gudang_inventory_by_role($row->id_gudang)->result());
      }
    
      $i++;
    }
    $data['data_barang'] = $gd;
      $this->load->view('logistik_farmasi/Frmvstok_optik',$data);
    }

  function index2()
  {
    $data['title'] = 'Stok Barang';
    $data['select_gudang'] = $this->Frmmstok_optik->get_data_gudang()->result();
    $data['data_barang'] = $this->Frmmstok_optik->getdata_gudang_inventory()->result();
    
    $this->load->view('logistik_farmasi/Frmvlapstok',$data);
  }

  public function get_data_detail_gudang(){
    $nm_gudang=$this->input->post('nm_gudang');
    $datajson=$this->Frmmdistribusi->getdata_gudang_inventory($nm_gudang)->result();
    echo json_encode($datajson);
  }

  public function exceldown($nm_gudang){
    $data['title'] = 'Laporan Gudang RS Khusus Mata';
    $nm_gudangreal=str_ireplace("%20"," ",$nm_gudang);    
    $namars=$this->config->item('namars');
    $alamat=$this->config->item('alamat');
    $kota_kab=$this->config->item('kota');
      
    $nm_gudang=$this->input->post('nm_gudang');
    $datajson=$this->Frmmstok_optik->get_data_gudang_detail($nm_gudangreal)->result();
    //print_r($datajson);break;
    ////EXCEL 
    $this->load->library('Excel');  
       
    // Create new PHPExcel object  
    $objPHPExcel = new PHPExcel();
    
    $objPHPExcel->getProperties()->setCreator($namars)  
            ->setLastModifiedBy($namars)  
            ->setTitle("Laporan Gudang RS Khusus Mata ".$namars)  
            ->setSubject("Laporan Gudang RS Khusus Mata ".$namars." Document")  
            ->setDescription("Laporan Gudang RS Khusus Mata ".$namars." for Office 2007 XLSX, generated by HMIS.")  
            ->setKeywords($namars)  
            ->setCategory("Laporan Gudang RS Khusus Mata");  
    
    $objReader= PHPExcel_IOFactory::createReader('Excel2007');
    $objReader->setReadDataOnly(true);
    $date=date('Y-m-d');
        $date_title=date('d F Y', strtotime($date));     
      
    $objPHPExcel=$objReader->load(APPPATH.'third_party/log_farm_stok_gudang.xlsx');
        // Set active sheet index to the first sheet, so Excel opens this as the first sheet  
    $objPHPExcel->setActiveSheetIndex(0);  
        // Add some data  
    $objPHPExcel->getActiveSheet()->SetCellValue('A1', $data['title'].' '.$nm_gudangreal);
    $objPHPExcel->getActiveSheet()->SetCellValue('A2', 'Tanggal : '.$date_title);
    
    $i=1;
    $rowCount = 5;$qtytot=0;
    foreach($datajson as $row){
      $qtytot+=$row->qty;
      $objPHPExcel->getActiveSheet()->SetCellValue('A'.$rowCount, $i);
      $objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, $row->batch_no);
      //SetCellValue('B'.$rowCount, $row->no_medrec);
      $objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, $row->nm_item);
      $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowCount, $row->qty);
      $objPHPExcel->getActiveSheet()->SetCellValue('E'.$rowCount, $row->expire_date);
      $i++;
      
      $rowCount++;
    }
    
    $objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, 'Total');
        $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowCount, $qtytot);
        $objPHPExcel->getActiveSheet()->getStyle('D'.$rowCount)->applyFromArray(
            array(
          'fill' => array(
              'type' => PHPExcel_Style_Fill::FILL_SOLID,
              'color' => array('rgb' => 'C1B2B2')
          )
            )
        );
        
          
        
    header('Content-Disposition: attachment;filename="Excel_Gudang_'.$date.'_'.$nm_gudangreal.'.xlsx"');  
        
    $objPHPExcel->getActiveSheet()->setTitle($namars);  
                   
    // Redirect output to a client’s web browser (Excel2007)  
    //clean the output buffer  
    ob_end_clean();  
       
    //this is the header given from PHPExcel examples.   
    //but the output seems somewhat corrupted in some cases.  
    //header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');  
    //so, we use this header instead.  
    header('Content-type: application/vnd.ms-excel');  
    header('Cache-Control: max-age=0');  
       
    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');  
    $objWriter->save('php://output');
  }

    public function exceldown_so($nm_gudang){
        $data['title'] = 'Format Khusus Stok Opname RS Khusus Mata';
        $nm_gudangreal=str_ireplace("%20"," ",$nm_gudang);
        $namars=$this->config->item('namars');
        $alamat=$this->config->item('alamat');
        $kota_kab=$this->config->item('kota');

        $nm_gudang=$this->input->post('nm_gudang');
        $datajson=$this->Frmmstok_optik->get_data_gudang_detail($nm_gudangreal)->result();
        //print_r($datajson);break;
        ////EXCEL
        $this->load->library('Excel');

        // Create new PHPExcel object
        $objPHPExcel = new PHPExcel();

        $objPHPExcel->getProperties()->setCreator($namars)
            ->setLastModifiedBy($namars)
            ->setTitle("Laporan Gudang RS Khusus Mata ".$namars)
            ->setSubject("Laporan Gudang RS Khusus Mata ".$namars." Document")
            ->setDescription("Laporan Gudang RS Khusus Mata ".$namars." for Office 2007 XLSX, generated by HMIS.")
            ->setKeywords($namars)
            ->setCategory("Laporan Gudang RS Khusus Mata");

        $objReader= PHPExcel_IOFactory::createReader('Excel2007');
        $objReader->setReadDataOnly(true);
        $date=date('Y-m-d');
        $date_title=date('d F Y', strtotime($date));

        $objPHPExcel=$objReader->load(APPPATH.'third_party/log_farm_stok_opname.xlsx');
        // Set active sheet index to the first sheet, so Excel opens this as the first sheet  
        $objPHPExcel->setActiveSheetIndex(0);
        // Add some data  
        /*$objPHPExcel->getActiveSheet()->SetCellValue('A1', $data['title'].' '.$nm_gudangreal);
        $objPHPExcel->getActiveSheet()->SetCellValue('A2', 'Tanggal : '.$date_title);*/

        $i=1;
        $rowCount = 2;$qtytot=0;
        foreach($datajson as $row){
            $qtytot+=$row->qty;
            $objPHPExcel->getActiveSheet()->SetCellValue('A'.$rowCount, $row->id_obat);
            $objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, $row->id_inventory);
            $objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, $row->batch_no);
            //SetCellValue('B'.$rowCount, $row->no_medrec);
            $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowCount, $row->nm_obat);
            $objPHPExcel->getActiveSheet()->SetCellValue('E'.$rowCount, $row->hargabeli);
            $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowCount, $row->hargajual);
            $objPHPExcel->getActiveSheet()->SetCellValue('G'.$rowCount, $row->jenis_obat);
            $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowCount, $row->expire_date);
            $objPHPExcel->getActiveSheet()->SetCellValue('I'.$rowCount, $row->qty);
            $objPHPExcel->getActiveSheet()->SetCellValue('J'.$rowCount, "0");
            $i++;

            $rowCount++;
        }

        /*$objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, 'Total');
            $objPHPExcel->getActiveSheet()->SetCellValue('E'.$rowCount, $qtytot);
            $objPHPExcel->getActiveSheet()->getStyle('E'.$rowCount)->applyFromArray(
                array(
              'fill' => array(
                  'type' => PHPExcel_Style_Fill::FILL_SOLID,
                  'color' => array('rgb' => 'C1B2B2')
              )
                )
            );*/

        $objPHPExcel->getActiveSheet()->setTitle($namars);

        //this is the header given from PHPExcel examples.
        //but the output seems somewhat corrupted in some cases.
        //header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        //so, we use this header instead.
        header('Content-type: application/vnd.ms-excel');
        header('Cache-Control: max-age=0');

        $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        // Redirect output to a client’s web browser (Excel2007)
        //clean the output buffer
        ob_end_clean();
        // We'll be outputting an excel file
        header('Content-type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename="Excel_SO_'.$date.'_'.$nm_gudangreal.'.xlsx"');
        //$objWriter->save('php://output');
        $this->SaveViaTempFile($objWriter);
        //$objWriter->save(APPPATH.'download/logistik_farmasi/Excel_Gudang_'.$date.'_'.$nm_gudangreal.'.xlsx');
    }

  public function exceldown_hasilso($nm_gudang){
    $nm_gudangreal=str_ireplace("%20"," ",$nm_gudang);    
    $data['title'] = 'Laporan Hasil SO RS Khusus Mata '.$nm_gudangreal;
    $namars=$this->config->item('namars');
    $alamat=$this->config->item('alamat');
    $kota_kab=$this->config->item('kota');
      
    $nm_gudang=$this->input->post('nm_gudang');
    $datajson=$this->Frmmstok_optik->get_last_so_by_gudang_name($nm_gudangreal)->result();
    //print_r($datajson);break;
    ////EXCEL 
    $this->load->library('Excel');  
       
    // Create new PHPExcel object  
    $objPHPExcel = new PHPExcel();
    
    $objPHPExcel->getProperties()->setCreator($namars)  
            ->setLastModifiedBy($namars)  
            ->setTitle("Laporan Hasil SO RS Khusus Mata ".$namars."  ".$nm_gudang)  
            ->setSubject("Laporan Hasil SO RS Khusus Mata ".$namars." Document")  
            ->setDescription("Laporan Hasil SO RS Khusus Mata ".$namars." for Office 2007 XLSX, generated by HMIS.")  
            ->setKeywords($namars)  
            ->setCategory("Laporan Hasil SO RS Khusus Mata");
    
    $objReader= PHPExcel_IOFactory::createReader('Excel2007');
    $objReader->setReadDataOnly(true);
    $date=date('Y-m-d');
        $date_title=date('d F Y', strtotime($date));     
      
    $objPHPExcel=$objReader->load(APPPATH.'third_party/log_farm_hasil_so.xlsx');
        // Set active sheet index to the first sheet, so Excel opens this as the first sheet  
    $objPHPExcel->setActiveSheetIndex(0);  
        // Add some data  
    $objPHPExcel->getActiveSheet()->SetCellValue('A1', $data['title'].' '.$nm_gudangreal);
    $objPHPExcel->getActiveSheet()->SetCellValue('A2', 'Tanggal : '.$date_title);
    
    $i=1;
    $rowCount = 5;$qtytot=0;
    foreach($datajson as $row){
      $qtytot+=$row->qty;
      $objPHPExcel->getActiveSheet()->SetCellValue('A'.$rowCount, $row->id_obat);
      $objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, $row->batch_no);
      //SetCellValue('B'.$rowCount, $row->no_medrec);
      $objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, $row->nm_obat);
      $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowCount, $row->hargabeli);
      $objPHPExcel->getActiveSheet()->SetCellValue('E'.$rowCount, $row->hargajual);
      $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowCount, $row->jenis_obat);
      $objPHPExcel->getActiveSheet()->SetCellValue('G'.$rowCount, $row->expire_date);
      $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowCount, $row->qty);
      $i++;
      
      $rowCount++;
    }
    
    $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowCount, 'Total');
    $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowCount, $qtytot);
    $objPHPExcel->getActiveSheet()->getStyle('F'.$rowCount)->applyFromArray(
        array(
      'fill' => array(
          'type' => PHPExcel_Style_Fill::FILL_SOLID,
          'color' => array('rgb' => 'C1B2B2')
      )
        )
    );
        
          
        
    header('Content-Disposition: attachment;filename="Excel_Gudang_'.$date.'_'.$nm_gudangreal.'.xlsx"');  
        
    $objPHPExcel->getActiveSheet()->setTitle($namars);  
                   
    // Redirect output to a client’s web browser (Excel2007)  
    //clean the output buffer  
    ob_end_clean();  
       
    //this is the header given from PHPExcel examples.   
    //but the output seems somewhat corrupted in some cases.  
    //header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');  
    //so, we use this header instead.  
    header('Content-type: application/vnd.ms-excel');  
    header('Cache-Control: max-age=0');  
       
    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');  
    $objWriter->save('php://output');
  }

  public function stokOpname(){
      $data['title'] = 'Input Stock Opname';

      $userid = $this->session->userid;
      $group = $this->Frmmpo->getIdGudang($userid)->id_gudang;

      $data['data_so'] = $this->Frmmstok_optik->get_last_so($group)->result();
      $this->load->view('logistik_farmasi/frmvstokopname',$data);
  }

  public function insert_stokopname(){
      $userid = $this->session->userid;
      $group = $this->Frmmpo->getIdGudang($userid)->id_gudang;

      $data['id_obat'] = $this->input->post('id_obat');
      $data['hargabeli'] = $this->input->post('biaya_obat');
      $data['hargajual'] = $this->input->post('harga_jual');
      $data['expire_date'] = $this->input->post('expire_date');
      $data['batch_no'] = $this->input->post('batch_no');
      $data['qty'] = $this->input->post('qty');
      $data['jenis_obat'] = $this->input->post('jenis_obat');
      $data['created_date'] = date('Y-m-d h:i:s');
      $data['id_gudang'] = $group;

      $save = $this->Frmmstok_optik->insert_stokopname($data);
      redirect('logistik_farmasi/Frmcstok/stokOpname');
  }

  public function edit_stokopname(){
      $userid = $this->session->userid;
      $group = $this->Frmmpo->getIdGudang($userid)->id_gudang;

      $data['id_obat'] = $this->input->post('id_obat');
      $data['hargabeli'] = $this->input->post('biaya_obat');
      $data['hargajual'] = $this->input->post('harga_jual');
      $data['expire_date'] = $this->input->post('expire_date');
      $data['batch_no'] = $this->input->post('batch_no');
      $data['qty'] = $this->input->post('qty');
      $data['jenis_obat'] = $this->input->post('jenis_obat');
      $data['created_date'] = date('Y-m-d h:i:s');
      $data['id_gudang'] = $group;

      $save = $this->Frmmstok_optik->edit_stokopname($data);
      redirect('logistik_farmasi/Frmcstok/stokOpname');
  }

  public function delete_stokopname(){
      $data['id_obat'] = $this->input->post('id_obat');
      $data['batch_no'] = $this->input->post('batch_no');

      $delete = $this->Frmmstok_optik->delete_stokopname($data);
      redirect('logistik_farmasi/Frmcstok/stokOpname');
  }

  public function edit_hasil_so($id_obat){
      $data['title'] = 'Edit Stock Opname';
      $userid = $this->session->userid;
      $group = $this->Frmmpo->getIdGudang($userid)->id_gudang;

      $data['itemso'] = $this->Frmmstok_optik->get_item_so($id_obat, $group)->row();
      $data['jenis'] = $this->Frmmstok_optik->get_new_jenisobat()->result();

      $this->load->view('logistik_farmasi/Frmveditstokopname', $data);
  }

    static function SaveViaTempFile($objWriter){
        $filePath = sys_get_temp_dir() . "/" . rand(0, getrandmax()) . rand(0, getrandmax()) . ".tmp";
        $objWriter->save($filePath);
        readfile($filePath);
        unlink($filePath);
    }

    function get_data_edit_obat(){
        $idobat = $this->input->post('id_obat');
        $idinventory = $this->input->post('id_inventory');

        $datajson=$this->Frmmstok_optik->get_data_obat($idobat, $idinventory)->result();
        echo json_encode($datajson);
    }

    function edit_obat(){
        $where = array(
            'id_obat' => $this->input->post('edit_id_obat'),
            'id_inventory' => $this->input->post('edit_id_inventory')
        );

        $data = array(
            'batch_no' => $this->input->post('edit_batch'),
            'expire_date' => $this->input->post('edit_ed')
        );

        $this->db->update('gudang_inventory', $data, $where);

        redirect('logistik_farmasi/Frmcstok');
    }

    function upload_so_page(){
        $data = array(
            'title' => 'Upload Excel Hasil SO',
            'gudang' => $this->Frmmamprah->get_gudang_tujuan()->result()
        );

        $this->load->view('logistik_farmasi/Frmvuploadexcel',$data);
    }

    public function proses_upload(){
        //echo "<pre>".print_r($_POST)."</pre>";
        $this->load->library('excel');

        $msg = "";
        $gudang = $this->input->post('gudang');

        if(isset($_FILES["file"]["name"])) {
            $path = $_FILES["file"]["tmp_name"];
            $object = PHPExcel_IOFactory::load($path);
            foreach($object->getWorksheetIterator() as $worksheet) {

                $highestRow = $worksheet->getHighestRow();
                $highestColumn = $worksheet->getHighestColumn();

                for($row=2; $row<=$highestRow; $row++) {

                    $id_obat = $worksheet->getCellByColumnAndRow(0, $row)->getValue();
                    $batch_no = $worksheet->getCellByColumnAndRow(1, $row)->getValue();
                    $id_gudang = $gudang;
                    $expire_date = $worksheet->getCellByColumnAndRow(6, $row)->getValue();
                    $qty = $worksheet->getCellByColumnAndRow(7, $row)->getValue();
                    $quantity_retur = 0;

                    $upload[] = array(
                        'id_obat'       => $id_obat,
                        'batch_no'      => $batch_no,
                        'id_gudang'     => $id_gudang,
                        'expire_date'   => $expire_date,
                        'qty'           => $qty,
                        'quantity_retur'=> $quantity_retur
                    );
                }
            }
            $this->Frmmstok_optik->importData($upload);
            $msg =  ' <div class="alert alert-success alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <i class="icon fa fa-check"></i>Data berhasil diupload...
                              </div>';
        }else{
            $msg =  ' <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <i class="icon fa fa-ban"></i>Oops!! Terjadi Kesalahan...
                      </div>';
        }

        $data = array(
            'title' => 'Upload Excel Hasil SO',
            'gudang' => $this->Frmmamprah->get_gudang_tujuan()->result()
        );

        $this->session->set_flashdata('alert_msg', $msg);
        $this->load->view('logistik_farmasi/Frmvuploadexcel', $data);
        //echo "<pre>".print_r($upload)."</pre>";
    }

}
?>